galaxy_info:
  author: P14-Lab
  description: Workstation configuration role
  company: MyCompany
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags: []

dependencies: []